### PR TITLE
Resolve anchors main

### PR DESCRIPTION
**Pull request by loicdrbx**
This update enables allow persistent cloud anchors to be resolved on the Tour app. Previously, this was only possible in the demo and Tour Manager (admin) app. 

Since the database is not yet incorporated, the Id for the cloud anchor one wants to resolve must be hard-coded (see PersistentCloudAnchorsController.cs, lines 170-179).

### CODE REVIEW

**Comment by loicdrbx** [comment]
@Angelica-P I'm going to need help figuring out the CI issues. The app builds and runs fine on my local machine and phone.

**Comment by Angelica-P** [comment]
The issue is that when it runs a build there's a difference between GvhProjectSettings.xml files. It looks like it's adding a line about google analytics.
If you add that line to your file and build and run the app does it still work?
`<projectSetting name="com.google.external-dependency-managerAnalyticsEnabled" value="False" />`

**Comment by loicdrbx** [comment]
> The issue is that when it runs a build there's a difference between GvhProjectSettings.xml files. It looks like it's adding a line about google analytics. If you add that line to your file and build and run the app does it still work? `<projectSetting name="com.google.external-dependency-managerAnalyticsEnabled" value="False" />`

I changed update the file and the CI still fails. I think it has to do with fact I used a different unity version than the project started with. Is there a way to update the unity version the CI runs with?

See the discussion on this issue here: [https://github.com/game-ci/unity-builder/issues/121](https://github.com/game-ci/unity-builder/issues/121)

**Comment by AlanH25** [comment]
Feature appears to work as planned. Tested it and was able to create and resolve anchors with the Admin app, and was able to resolve them in the main app (with Loic's help of course)

**Pull request merged**
